### ISSUE TITLE
Update to OpenSMTPD 5.7.3

### ISSUE THREAD

**Issue by joelchen** [vixns/docker-opensmtpd#1]
Current image of vixns/opensmtpd contains OpenSMTPD 5.4.2. Would like to have the latest version of OpenSMTPD if possible.

**Comment by vixns** [comment]
Updated to 5.7.3p1, also add an explicit image tag

`docker run -p 25:25 vixns/opensmtpd:5.7.3p1`

**Comment by joelchen** [comment]
Thank you @vixns for the quick update!
